
# Meta config for choosing which analysis to launch
# Give which project it's related to
# If launching an already made config, give the path, can be None

project_name: BetaMouv
config_log: None

# Analysis step to launch
# Boolean only

steps:
  prediction: true
  preprocessing: false
  compute_metrics: false

  make_figures:
    single_subject: false
    single_trial: false
    inter_subject: false


