# filter criteria before launching preprocessing / analysis etc...

# movement type
mvt_type: 
  CONTRA: t
  IPSI: t
  UNKNOWN: t

# condition
condition: 
  CHR: t
  CTRL: t

# subject
subject: 
  "#517": 
  "#525": 
  "#521": 
  "#531": 
  "#527": 
  "#516": 


