# filter criteria before launching preprocessing / analysis etc...

# movement type
mvt_type: 
  CONTRA: t
  IPSI: 
  UNKNOWN:

# condition
condition: 
  CHR: t
  CTRL: 

# subject
subject: 
  "#517": t
  "#525": 
  "#521": 
  "#531": t
  "#527": 
  "#516": 


