# # Input data
# model: "/media/filer2/T4b/UserFolders/Poemiti/Reaching-DLC-model-main/data/model/DLC-Poe-2026-03-27/"
# raw_videos: "/media/filer2/T4b/UserFolders/Raphael/Raphael_M2_2024/Opto_SkilledReaching_2024_experiments/MOVIES/"

# # Output folder
# data_root: ./data
# database: "data/BetaMouv/database"

# # Inter-rat
# inter_rat: "data/BetaMouv/inter_rat"

# # Per-rat
# rat_root: "data/BetaMouv/rat_#531"
# raw_clips: "data/BetaMouv/rat_#531/raw_clips"

# processed: "data/BetaMouv/rat_#531/processed"
# dlc: "data/BetaMouv/rat_#531/processed/dlc"
# metrics: "data/BetaMouv/rat_#531/processed/metrics"
# luminosity: "data/BetaMouv/rat_#531/processed/luminosity"
# preprocessing: "data/BetaMouv/rat_#531/processed/preprocessing"
# analysis: "data/BetaMouv/rat_#531/analysis_finger_3"


# Input data
model: "/media/filer2/T4b/UserFolders/Poemiti/Reaching-DLC-model-main/data/model/DLC-Poe-2026-03-27/"
raw_videos: "/media/filer2/T4b/UserFolders/Raphael/Raphael_M2_2024/Opto_SkilledReaching_2024_experiments/MOVIES/"

# Output folder
data_root: ./data/{project_name}
database: "{data_root}/database"

# trials metadata
trials_metadata: "{data_root}/trials_metadata"

# Per-subject
rat_root: "{data_root}/rat_{rat_name}"

raw: "{rat_root}/raw"
dlc: "{raw}/dlc"
luminosity: "{raw}/luminosity"
preprocessing: "{raw}/preprocessing"

analysis: "{rat_root}/analysis_{bodypart}"
