# Hyperparameters (that don't change)

bodyparts: ["finger_2", "finger_3", "soft_pad"]

# Parameters for preprocessing
laser_on_duration: 0.325  # sec (0.3 of laser + 0.025 from pad_off to laser stim)
gap_scale: 0.15 # for outlier detection
distance_thresh: 0.6 # for outlier detection (cm)
max_outlier: 10 
shift_ref: "./data/BetaMouv/camera_shift/#517_CHR_CONTRA_Beta_RightHemi_leftView_high_LaserOff_2024-07-05.png"

# General info on protocole setup
fps: 125
lever_position: [55, 230]
pad_position: [315, 348]
frame_width_px: 512
frame_height_px: 512

