# BetaMouv Subject
# 8 rats have been train to perform the reaching task

"#516":
  hemi: 
    CHR: LeftHemi
    CTRL: RightHemi
  handedness: ambi

"#517":
  hemi: 
    CHR: RightHemi
    CTRL: LeftHemi
  handedness: ambi

"#521":
  hemi: 
    CHR: LeftHemi
    CTRL: RightHemi
  handedness: right

"#525":
  hemi: 
    CHR: RightHemi
    CTRL: LeftHemi
  handedness: ambi

"#527":
  hemi: 
    CHR: LeftHemi
    CTRL: RightHemi
  handedness: right

"#531":
  hemi: 
    CHR: RightHemi
    CTRL: LeftHemi
  handedness: left

"#529":
  hemi: 
    CHR: RightHemi
    CTRL: LeftHemi
  handedness: ambi

